### ISSUE TITLE
Cannot upload RGB images to OMERO

### ISSUE THREAD

**Issue by ctrueden** [scifio/scifio-omero#5]
```
[ERROR] Exception
java.io.IOException: io.scif.img.ImgIOException: io.scif.FormatException: Error writing to OMERO: imageIndex=0, planeIndex=1
	at net.imagej.DefaultDatasetService.save(DefaultDatasetService.java:299) ~[imagej-common-0.7.2.jar:0.7.2]
	at net.imagej.DefaultDatasetService.save(DefaultDatasetService.java:283) ~[imagej-common-0.7.2.jar:0.7.2]
	at net.imagej.omero.SaveToOMERO.run(SaveToOMERO.java:66) ~[imagej-omero-0.1.0.jar:0.1.0]
	at org.scijava.command.CommandModule.run(CommandModule.java:201) [scijava-common-2.22.3.jar:2.22.3]
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:167) [scijava-common-2.22.3.jar:2.22.3]
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:126) [scijava-common-2.22.3.jar:2.22.3]
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:65) [scijava-common-2.22.3.jar:2.22.3]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_55]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_55]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_55]
	at java.lang.Thread.run(Thread.java:744) [na:1.7.0_55]
Caused by: io.scif.img.ImgIOException: io.scif.FormatException: Error writing to OMERO: imageIndex=0, planeIndex=1
	at io.scif.img.ImgSaver.writePlanes(ImgSaver.java:655) ~[scifio-0.14.1.jar:0.14.1]
	at io.scif.img.ImgSaver.writeImg(ImgSaver.java:516) ~[scifio-0.14.1.jar:0.14.1]
	at io.scif.img.ImgSaver.writeImg(ImgSaver.java:502) ~[scifio-0.14.1.jar:0.14.1]
	at io.scif.img.ImgSaver.writeImg(ImgSaver.java:472) ~[scifio-0.14.1.jar:0.14.1]
	at io.scif.img.ImgSaver.writeImg(ImgSaver.java:452) ~[scifio-0.14.1.jar:0.14.1]
	at io.scif.img.ImgSaver.saveImg(ImgSaver.java:157) ~[scifio-0.14.1.jar:0.14.1]
	at io.scif.img.ImgSaver.saveImg(ImgSaver.java:141) ~[scifio-0.14.1.jar:0.14.1]
	at net.imagej.DefaultDatasetService.save(DefaultDatasetService.java:296) ~[imagej-common-0.7.2.jar:0.7.2]
	... 10 common frames omitted
Caused by: io.scif.FormatException: Error writing to OMERO: imageIndex=0, planeIndex=1
	at io.scif.omero.OMEROFormat.writerException(OMEROFormat.java:635) ~[scifio-omero-0.5.1.jar:0.5.1]
	at io.scif.omero.OMEROFormat.access$300(OMEROFormat.java:73) ~[scifio-omero-0.5.1.jar:0.5.1]
	at io.scif.omero.OMEROFormat$Writer.writePlane(OMEROFormat.java:512) ~[scifio-omero-0.5.1.jar:0.5.1]
	at io.scif.AbstractWriter.savePlane(AbstractWriter.java:168) ~[scifio-0.14.1.jar:0.14.1]
	at io.scif.AbstractWriter.savePlane(AbstractWriter.java:159) ~[scifio-0.14.1.jar:0.14.1]
	at io.scif.img.ImgSaver.writePlanes(ImgSaver.java:652) ~[scifio-0.14.1.jar:0.14.1]
	... 17 common frames omitted
Caused by: omero.ApiUsageException: null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.7.0_55]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) ~[na:1.7.0_55]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.7.0_55]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526) ~[na:1.7.0_55]
	at java.lang.Class.newInstance(Class.java:374) ~[na:1.7.0_55]
	at IceInternal.BasicStream.createUserException(BasicStream.java:2615) ~[omero-client-dev_5_0-ice35-b287.jar:na]
	at IceInternal.BasicStream.access$300(BasicStream.java:12) ~[omero-client-dev_5_0-ice35-b287.jar:na]
	at IceInternal.BasicStream$EncapsDecoder10.throwException(BasicStream.java:3099) ~[omero-client-dev_5_0-ice35-b287.jar:na]
	at IceInternal.BasicStream.throwException(BasicStream.java:2077) ~[omero-client-dev_5_0-ice35-b287.jar:na]
	at IceInternal.Outgoing.throwUserException(Outgoing.java:538) ~[omero-client-dev_5_0-ice35-b287.jar:na]
	at omero.api._RawPixelsStoreDelM.setPlane(_RawPixelsStoreDelM.java:1668) ~[omero-client-dev_5_0-ice35-b287.jar:na]
	at omero.api.RawPixelsStorePrxHelper.setPlane(RawPixelsStorePrxHelper.java:8082) ~[omero-client-dev_5_0-ice35-b287.jar:na]
	at omero.api.RawPixelsStorePrxHelper.setPlane(RawPixelsStorePrxHelper.java:8044) ~[omero-client-dev_5_0-ice35-b287.jar:na]
	at io.scif.omero.OMEROFormat$Writer.writePlane(OMEROFormat.java:509) ~[scifio-omero-0.5.1.jar:0.5.1]
	... 20 common frames omitted
```

**Comment by ctrueden** [comment]
Migrated to imagej/imagej-omero#55
